# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.8"
    - nodejs_version: "0.11"

# Allow failing jobs for bleeding-edge Node.js versions.
matrix:
  allow_failures:
    - nodejs_version: "0.11"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff.
  - npm install
  # Grunt-specific stuff.
  - npm install -g grunt-cli
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"

build_script:
  #grunt
  - grunt