
init:
  - git config --global core.autocrlf input


environment:
  matrix:  
    - nodejs_version: "0.11"

install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff.
  - npm install
  # Grunt-specific stuff.
  - npm install -g grunt-cli
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958

version: "{build}"

build_script:
  #grunt
  - grunt

  artifacts:
   - path: wwwroot